# Generated by Django 5.0.3 on 2024-04-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.AlterField(
            model_name='cart',
            name='furniture_item',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.furniture_item'),
        ),
    ]
