# Generated by Django 4.2.11 on 2024-04-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='furniture_item',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
