# Generated by Django 4.2.11 on 2024-04-17 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_cart_quantity_cartitem'),
        ('main_app', '0008_alter_furniture_item_quantity'),
    ]

    operations = [
    ]
